### PR TITLE
Compile using dockcross browser asmjs

### PR DESCRIPTION
**Pull request by jcfr**
This PR updates the project to:
* build using [fork of DCMTK](https://github.com/jcfr/DCMTK/compare/cece99c...jcfr:emscripten-2016-11-02-cece99c) based on DCMTK-3.6.1_20161102
* build using latest Emscripten SDK (1.36.14-64bit) provided by [dockcross](https://github.com/dockcross/dockcross#dockcross)
* require CMake 3.7
* add continuous integration using CircleCI (it currently only tests the build)
* build using updated dependencies:
  * libpng: 1.6.10 to 1.6.26
  * libxml2: 2.9.1 to 2.9.4

### CODE REVIEW

**Comment by pieper** [comment]
Looks cool Jc - 👍

**Comment by jcfr** [comment]
Thanks for the review.

**Comment by jcfr** [comment]
Worth noting that the dcmjs.js  is also available in the build artifacts in circleci report

**Comment by jcfr** [comment]
dcmjs.org updated in https://github.com/commontk/dcmjs.org/commit/e0baf8222c3657f79ea6187971f0ba2aa64c1f57

**Pull request merged**
