### PR TITLE
Fix libxml build to support dsr2xml

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
@fedorov With this I am able to enable xml2dsr `-DBUILD_dsr2xml_APP:BOOL=1` based of DCMTK 3.6.1:

```
emscripten@8b07898689b1:/work/dcmjs-build$ nodejs dcmjs-build/bin/dcmjs.js list
dcm2pnm
dcmdump
dcm2xml
dcmftest
xml2dcm
xml2dsr

emscripten@8b07898689b1:/work/dcmjs-build$ nodejs dcmjs-build/bin/dcmjs.js xml2dsr --help
$dcmtk: xml2dsr v3.6.1 DEV $

xml2dsr: Convert XML document to DICOM SR file
usage: xml2dsr [options] xmlfile-in dsrfile-out

parameters:
  xmlfile-in                    XML input filename to be converted (stdin: "-")
  dsrfile-out                   DICOM SR output filename

general options:
  -h     --help                 print this help text and exit
         --version              print version information and exit
         --arguments            print expanded command line arguments
  -q     --quiet                quiet mode, print no warnings and errors
  -v     --verbose              verbose mode, print processing details
  -d     --debug                debug mode, print debug information
  -ll    --log-level            [l]evel: string constant
                                (fatal, error, warn, info, debug, trace)
                                use level l for the logger
  -lc    --log-config           [f]ilename: string
                                use config file f for the logger
input options:
  encoding:
    +Ee  --template-envelope    template element encloses content items
processing options:
  validation:
    +Vs  --validate-schema      validate XML document against Schema
                                (not with --template-envelope)
[...]
```

**Comment by jcfr** [comment]
Would appreciate if you could test :+1:

**Comment by jcfr** [comment]
> should be able to test by the end of the day.

Great :+1: 

To summarize:
1. This PR (#24) support building `xml2dsr` and `dsr2xml` with DCMTK 3.6.1
2. This other PR (#22) support building `xml2dsr` and `dsr2xml` with DCMTK 3.6.4

Would be great if you could test both.

**Comment by fedorov** [comment]
This branch does not seem to work:

```
[7/7] Creating library symlink lib/libdcmpstat.so.10 lib/libdcmpstat.so
[12/19] No install step for 'DCMTK'
[14/19] Performing configure step for 'dcmjs'
loading initial cache file /work/dcmjs-build/dcmjs-prefix/tmp/dcmjs-cache-Release.cmake
-- Setting download cache directory to: /work/dcmjs-build/dcmjs-build/../dcmjs-download-cache
-- Found Emscripten [1.37.37]
-- Configuring done
-- Generating done
-- Build files have been written to: /work/dcmjs-build/dcmjs-build
[15/19] Performing build step for 'dcmjs'
[1/1] Linking CXX executable bin/dcmjs.js
FAILED: bin/dcmjs.js
: && /emsdk_portable/sdk/em++  -Wno-warn-absolute-paths -s ALLOW_MEMORY_GROWTH=1 -s ASSERTIONS=1 --memory-init-file 0 -Wno-warn-absolute-paths -s ALLOW_MEMORY_GROWTH=1 -s ASSERTIONS=1 --memory-init-file 0 -DNDEBUG -O2  -O2 src/CMakeFiles/dcmjs.dir/dcmjs.cpp.o  -o bin/dcmjs.js  ../DCMTK-build/lib/libdcm2xml.so.3.6.1 ../DCMTK-build/lib/libdcmdump.so.3.6.1 ../DCMTK-build/lib/libdcmftest.so.3.6.1 ../DCMTK-build/lib/libxml2dcm.so.3.6.1 ../DCMTK-build/lib/libdcm2pnm.so.3.6.1 ../DCMTK-build/lib/libdsr2xml.so.3.6.1 lib/libdcmjs_1_pre_js.a --pre-js "/work/javascripts/pre.js" ../DCMTK-build/lib/libdcmsr.so.3.6.1 ../LibXml2/.libs/libxml2.a ../DCMTK-build/lib/libdcmimage.so.3.6.1 ../PNG-install/lib/libpng16.so ../DCMTK-build/lib/libdcmimgle.so.3.6.1 ../DCMTK-build/lib/libdcmdata.so.3.6.1 ../ZLIB-install/lib/libzlib.so ../DCMTK-build/lib/liboflog.so.3.6.1 ../DCMTK-build/lib/libofstd.so.3.6.1 && cd /work/dcmjs-build/dcmjs-build/src && /usr/bin/cmake -E copy /work/dcmjs-build/dcmjs-build/bin/dcmjs.js /work/dcmjs-build/dcmjs-build/src/dcmjs.bak && /bin/gzip -f /work/dcmjs-build/dcmjs-build/bin/dcmjs.js && /usr/bin/cmake -E copy /work/dcmjs-build/dcmjs-build/src/dcmjs.bak /work/dcmjs-build/dcmjs-build/bin/dcmjs.js
WARNING:root:not all asm.js optimizations are possible with ALLOW_MEMORY_GROWTH, disabling those. [-Walmost-asm]
error: Linking globals named 'xmlParserMaxDepth': symbol multiply defined!
ERROR:root:Failed to run llvm optimizations:
ninja: build stopped: subcommand failed.
FAILED: dcmjs-prefix/src/dcmjs-stamp/dcmjs-build
cd /work/dcmjs-build/dcmjs-build && /usr/bin/cmake --build . && /usr/bin/cmake -E touch /work/dcmjs-build/dcmjs-prefix/src/dcmjs-stamp/dcmjs-build
ninja: build stopped: subcommand failed.
```

**Comment by fedorov** [comment]
Sorry, I am proven again and again I am very bad in multitasking ... I was testing master :-(

Will redo.

**Comment by fedorov** [comment]
This branch seems to have the same issue as in https://github.com/commontk/dcmjs/pull/22#issuecomment-446757413. It looks like passing files through command line does not work.

**Comment by jcfr** [comment]
This topic has been integrated, it now supports filesystem IO using nodejs.

See https://github.com/commontk/dcmjs#file-io-using-node

**Pull request merged**
