### PR TITLE
Support use of dcmjs module using "require()"

### PR DESCRIPTION
**Pull request by jcfr**

### CODE REVIEW

**Comment by jcfr** [comment]
@dbousamra  Would be great if you could test and review

**Comment by jcfr** [comment]
Once integrated, we should also update [javascripts/utils.js](https://github.com/commontk/dcmjs.org/blob/gh-pages/javascripts/utils.js#L64-L66) and [dump/index.html](https://github.com/commontk/dcmjs.org/blob/gh-pages/dump/index.html#L18-L39)

**Comment by jcfr** [comment]
@tarinitorpe any objection if this get integrated. Thanks for your help reviewing

**Comment by tarinitorpe** [comment]
@jcfr I think it is a good upgrade! It would be much more easier to build it into other applications! (But as I mentioned previously I want to use it mostly in the browser and I am not sure it will help to import it into e.g. an angular web app!)

**Comment by jcfr** [comment]
Thanks for the review, I will go ahead and integrated then.

**Pull request merged**
